### ISSUE TITLE
Sleeping during a thunderstorm loops "The night has been skipped"

### ISSUE THREAD

**Issue by Krytic** [nkomarn/harbor#49]
We're running Harbor v1.6.2-SNAPSHOT on Minecraft 1.15.2. Our night-skip settings are:

```yaml
night-skip:
  enabled: true # Skip the night if a percentage of the players in a world are sleeping
  percentage: 50 # Percentage of players required to be sleeping to skip the night (0 - 100)
  time-rate: 70 # The amount of ticks added to the current time every tick when skipping the night
  daytime-ticks: 1200 # The time in ticks that Harbor considers day
  instant-skip: true # Instantly skip the night instead of showing the full animation
  proportional-acceleration: false # Increase the night skipping speed based on the amount of sleeping players
  clear-rain: true # Clear rain (if it's raining) when the night is skipped
  clear-thunder: true # Clear thunder (if it's thundering) when the night is skipped
  reset-phantom-statistic: false # Treats everyone online as if they have slept in the last 3 days after the night is skipped (check out /gamerule doInsomnia on 1.15+)
```

If we sleep during a thunderstorm, the following sequence of events occurs:
1) 50% of players begin to sleep
2) Night advances to day
3) We get a "The night has been skipped"
4) The thunderstorm has not been skipped, all players remain sleeping
5) Repeat 3 and 4 ad nauseum until players begin getting out of bed
6) If all players are sleeping, clear thunder, advance to day, and kick players from their beds.

I think intended behaviour should be that the thunderstorm is skipped and we go to morning, just like if it was night and we were sleeping.
