### ISSUE TITLE
Not Sending Chat Messages

### ISSUE THREAD

**Issue by DeJayDev** [nkomarn/harbor#56]
Running PaperSpigot 1.15.2 (Build 334) and Harbor 1.6.1:

Harbor does not send chat messages despite them being enabled. Screenshot of chat with no messages:

![](https://u.dejay.dev/😢✨🛒.png)

Config:
```yml
values:
  timer: 3 # How often (in seconds) to run the clock task (used to detect sleep, AFK players, time actionbar, etc.)
  percent: 30 # Percent of players that need to sleep to skip night (must be between 0 to 100)
  interval: 60 # Time skip interval that is added when the night get accelerated.

features:
  skip: true # Toggle night skipping feature. Configure amount of players needed to skip above (percent)
  weather: true # Clear weather when skipping night
  phantoms: false # Reset the sleep statistic (practically disables phantom spawns - false = no phantoms)
  bypass: true  # Toggle exclusion of operators/players with permission "harbor.bypass" from sleep count
  ignore: true  # Toggle exclusion of players in creative and spectator mode
  afk: true # Detect AFK players and remove them from the sleep count (Essentials API used for detection)
  notifier: true # Displays a notification when a new update is released

messages:
  chat:
    chat: true # Toggle chat messages
    skipped: # Night skipped chat messages
      - "&eThe night has been skipped."
      - "&eAhhh, finally morning."
      - "&eArghh, it's so bright outside."
    sleeping: "&e[player] is now sleeping ([sleeping]/[needed], [more] more needed to skip)." # Display which player went to bed
    left: "&e[player] got out of bed ([sleeping]/[needed], [more] more needed to skip)." # Display when a player left their bed
    accelerateNight: # Display when the night is being accelerated.
      - "&eYou look to the skies and see it's becoming daytime."
      - "&eYou feel the sky quickly lighten. It is now day."
  actionbar:
    actionbar: true # Enable/disable actionbar messages
    sleeping: "&e[sleeping] out of [needed] players are sleeping ([more] more needed to skip)." # Shown when some players are in bed
    everyone: "&eEveryone is sleeping. Sweet dreams!" # Shown when all players are in bed
  miscellaneous:
    prefix: "&8&l(&6&lHarbor&8&l)&r " # Prefix for Harbor command/miscellaneous messages
    permission: "&7Insufficient permissions." # Sent when player doesn't have permissions to run command
    unrecognized: "&7Unrecognized command." # Sent when command argument isn't recognized

blacklist: # Blacklist for worlds (Harbor will be disabled in these worlds)
  - "world_nether"
  - "world_the_end"

# Spooky controls (don't change)
version: 1.6
debug: false
```
